function_prefix = "fun"

[functions]
"get element by id" = "getElementById"
"set state" = "setState"

[commands]
"fun print" = ["console.log();", "left left"]
"assign" = " = "
"function" = ["function() {}", "left left left left"]
"constructor" = ["constructor(props) {}", "left enter", "super(props);", "enter"]
"constant" = "const "
"semi" = ["", "end", ";"]
"iffae" = ["if () {}", "left enter up home right right right right"]
"shells" = ["else {}", "left enter"]
"letter" = "let "
"lodge if" = "if "
"lodge else" = " else "
"lodge and" = " && "
"lodge or" = " || "
"variable" = "var "
"value true" = "true"
"value null" = "null"
"value false" = "false"
"right arrow" = " => "
"return" = "return "
"thissy" = "this."
"thissy props" = "this.props."
"thissy state" = "this.state"