title_contexts = [".rs"]
function_prefix = "fun"
template_prefix = "template"

[functions]
"unwrap" = "unwrap"
"parse" = "parse"
"lines" = "lines"
"to string" = "to_string"
"iter" = "iter"
"clone" = "clone"
"next" = "next"
"push" = "push"
"get" = "get"

[commands]
"fun print" = ["println!(\"{}\", );", "left left"]
"assign" = " = "
"function main" = ["fn main() {}", "left enter"]
"semi" = ["", "end", ";"]
"iffae" = ["if  {}", "left enter up home right right right"]
"shells" = ["else {}", "left enter"]
"lodge if" = "if "
"lodge else" = " else "
"lodge and" = " && "
"lodge or" = " || "
"use standard" = ["use std::;", "left"]
"for loop" = ["for  in  {}", "left enter up home right:4"]
"while loop" = ["while  {}", "left enter up home right:6"]
"letter" = "let "
"letter mute" = "let mut "
"value true" = "true"
"value false" = "false"
"right arrow" = " => "
"produces" = " -> "
"pattern match" = ["match  {}", "left enter up home right:6"]
"structure" = ["struct  {}", "left enter up home right:7"]
"enumerate" = ["enum  {}", "left enter up home right:5"]
"return" = "return "

[types]
"eye 3 2" = "i32"
"you 3 2" = "u32"
"string" = "str"

